backend_repo_url: "https://github.com/pravinmishraaws/book-review-app.git"
backend_app_port: 3001
db_host: "terraform-20251105084903474000000004.ca5ssik42y9m.us-east-1.rds.amazonaws.com"
db_port: 3306
db_user: "mysqladmin"
db_password: "SuperSecret123!"
db_name: "bookreviews_dev"
jwt_secret: "your_jwt_secret"
allowed_origins: "http://34.229.223.99:3000"
